name: Blog Posts

on:
  workflow_dispatch:
    inputs:
      name:
        description: '手动触发'
        required: true
        default: '文章列表'
  # Run workflow automatically
  schedule:
    # Runs every hour, on the hour
    - cron: '0 23 * * *'
permissions:
  contents: write # To write the generated contents to the readme
  
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          # comma-separated list of RSS feed urls
          feed_list: "https://blog.dragondyt.top/rss.xml"
